apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: graphtuitous 
spec:
  description: "graphtuitous built in App Studio"
  displayName: "graphtuitousÂ® - Multi-Component Demo"
  # displayName: "graphtuitous"
